---
all:
  hosts:
    nexus-01:
      ansible_host: 89.169.165.192
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: netology_yandex